//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./hello_types');
//HELPER FUNCTIONS AND STRUCTURES

Hello_hi_args = function(args) {
};
Hello_hi_args.prototype = {};
Hello_hi_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Hello_hi_args.prototype.write = function(output) {
  output.writeStructBegin('Hello_hi_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Hello_hi_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = args.success;
    }
  }
};
Hello_hi_result.prototype = {};
Hello_hi_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Hello_hi_result.prototype.write = function(output) {
  output.writeStructBegin('Hello_hi_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var tracing = require("../../lib/trace/tracing_types");
Hello___can__finagle__trace__v3___args = function(args) {
  this.options = null;
  if (args) {
    this.options = args.options;
  }
};
Hello___can__finagle__trace__v3___args.prototype = {};
Hello___can__finagle__trace__v3___args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == Thrift.Type.STRUCT) {
          this.options = new tracing.ConnectionOptions();
          this.options.read(input);
        } else {
          input.skip(ftype);
        }
        break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

Hello___can__finagle__trace__v3___args.prototype.write = function(output) {
  output.writeStructBegin('Hello___can__finagle__trace__v3___args');
  if (this.options !== null && this.options !== undefined) {
    output.writeFieldBegin('options', Thrift.Type.STRUCT, 1);
    this.options.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

Hello___can__finagle__trace__v3___result = function(args) {
  this.success = new tracing.UpgradeReply(args);
};
Hello___can__finagle__trace__v3___result.prototype = {};
Hello___can__finagle__trace__v3___result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }

    switch (fid)
    {
      case 0:
        if (ftype == Thrift.Type.STRUCT) {
          this.success = new tracing.UpgradeReply();
          this.success.read(input);
        } else {
          input.skip(ftype);
        }
        break;
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};
Hello___can__finagle__trace__v3___result.prototype.write = function(output) {
  output.writeStructBegin('Hello___can__finagle__trace__v3___result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

HelloClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
HelloClient.prototype = {};
HelloClient.prototype.seqid = function() { return this._seqid; }
HelloClient.prototype.new_seqid = function() { return this._seqid += 1; }

HelloClient.prototype.__can__finagle__trace__v3__ = function() {
  this._seqid = this.new_seqid();
  var output = new this.pClass(this.output);
  output.writeMessageBegin('__can__finagle__trace__v3__', Thrift.MessageType.CALL, this._seqid);
  var args = new Hello___can__finagle__trace__v3___args();
  args.options = new tracing.ConnectionOptions();
  args.write(output);
  output.writeMessageEnd();
  this.output.flush();
};

HelloClient.prototype.recv___can__finagle__trace__v3__ = function(input,mtype,rseqid) {
  var callback = function(res) {
    console.log(">>>>>>>>>>>"+res)
  };
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Hello___can__finagle__trace__v3___result();
  result.read(input);
  input.readMessageEnd();
  callback(result.success)
};

HelloClient.prototype.hi = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_hi();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_hi();
  }
};

HelloClient.prototype.send_hi = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('hi', Thrift.MessageType.CALL, this.seqid());
  var args = new Hello_hi_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

HelloClient.prototype.recv_hi = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new Hello_hi_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('hi failed: unknown result');
};
HelloProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
HelloProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

HelloProcessor.prototype.process_hi = function(seqid, input, output) {
  var args = new Hello_hi_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.hi.length === 0) {
    Q.fcall(this._handler.hi)
      .then(function(result) {
        var result = new Hello_hi_result({success: result});
        output.writeMessageBegin("hi", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("hi", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.hi(function (err, result) {
      if (err == null) {
        var result = new Hello_hi_result((err != null ? err : {success: result}));
        output.writeMessageBegin("hi", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("hi", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

